import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, AudioLines, Bell, Bot, Check, ChevronDown, ChevronRight, Clock3, Gauge, History, Home, Info, Landmark, LocateFixed, LockKeyhole, MapPin, Mic, Moon, Navigation, Pause, Plane, Play, RotateCcw, Route as RouteIcon, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkle, Square, Trash2, UserRound, Volume2, X } from "lucide-react";
import { Switch } from "@/components/ui/switch";
import { places, routes, trips } from "@/lib/mock-data";
import { AIMessage, BottomNavigation, DemoPill, FloatingCard, GlassCard, ListRow, LocationStatus, MetricCard, PrimaryButton, RouteCard, SecondaryButton, TripCard } from "@/components/mobile-ui";
import { MapContainer } from "@/components/map-visual";
import { cn } from "@/lib/utils";

type Screen = "splash"|"onboarding"|"permission"|"home"|"search"|"destination"|"routes"|"ai"|"navigation"|"complete"|"trips"|"tripDetail"|"replay"|"insights"|"profile"|"settings"|"privacy";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Aera — Intelligent Map Prototype" },
    { name: "description", content: "A premium AI-powered navigation and journey intelligence mobile prototype." },
    { property: "og:title", content: "Aera — Intelligent Map Prototype" },
    { property: "og:description", content: "Talk to your map, compare routes, and understand every journey." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: App,
});

function App(){
  const [screen,setScreen]=useState<Screen>("splash");
  const [previous,setPrevious]=useState<Screen>("home");
  const [onboarding,setOnboarding]=useState(0);
  const [selectedRoute,setSelectedRoute]=useState("fast");
  const [tripExpanded,setTripExpanded]=useState(false);
  const go=(next:Screen)=>{setPrevious(screen);setScreen(next)};
  const back=()=>setScreen(previous);
  const nav=(id:string)=>go(id==="trips"?"trips":id==="ai"?"ai":id==="profile"?"profile":"home");
  return <main className="min-h-dvh bg-stage font-sans text-foreground"><div className="mx-auto min-h-dvh max-w-[430px] overflow-hidden bg-background shadow-[0_0_80px_var(--stage-shadow)] sm:min-h-[880px] sm:my-6 sm:h-[calc(100vh-3rem)] sm:max-h-[920px] sm:rounded-[2.25rem] sm:border sm:border-border/60"><div key={screen} className="relative h-dvh min-h-[680px] animate-screen-in overflow-hidden sm:h-full sm:min-h-0">
    {screen==="splash"&&<Splash onContinue={()=>go("onboarding")}/>} 
    {screen==="onboarding"&&<Onboarding step={onboarding} next={()=>onboarding<2?setOnboarding(onboarding+1):go("permission")} skip={()=>go("permission")}/>} 
    {screen==="permission"&&<Permission onAllow={()=>go("home")} onSkip={()=>go("home")}/>} 
    {screen==="home"&&<HomeMap onSearch={()=>go("search")} onAI={()=>go("ai")} onProfile={()=>go("profile")} nav={nav}/>} 
    {screen==="search"&&<SearchScreen back={back} select={()=>go("destination")}/>} 
    {screen==="destination"&&<Destination back={back} directions={()=>go("routes")} ask={()=>go("ai")}/>} 
    {screen==="routes"&&<RouteComparison selected={selectedRoute} setSelected={setSelectedRoute} back={back} start={()=>go("navigation")}/>} 
    {screen==="ai"&&<AIAssistant back={()=>go("home")} nav={nav}/>} 
    {screen==="navigation"&&<ActiveNavigation expanded={tripExpanded} setExpanded={setTripExpanded} end={()=>go("complete")}/>} 
    {screen==="complete"&&<TripComplete detail={()=>go("tripDetail")} ask={()=>go("insights")}/>} 
    {screen==="trips"&&<TripHistory open={()=>go("tripDetail")} nav={nav}/>} 
    {screen==="tripDetail"&&<TripDetails back={back} replay={()=>go("replay")} insight={()=>go("insights")}/>} 
    {screen==="replay"&&<Replay back={back}/>} 
    {screen==="insights"&&<Insights back={back}/>} 
    {screen==="profile"&&<Profile openSettings={()=>go("settings")} openTrips={()=>go("trips")} openPrivacy={()=>go("privacy")} nav={nav}/>} 
    {screen==="settings"&&<Settings back={back} privacy={()=>go("privacy")}/>} 
    {screen==="privacy"&&<Privacy back={back}/>} 
  </div></div></main>
}

function Splash({onContinue}:{onContinue:()=>void}){return <button onClick={onContinue} className="relative flex h-full w-full flex-col items-center justify-center overflow-hidden bg-ink text-left" aria-label="Open Aera"><MapContainer mode="routes"/><div className="absolute inset-0 bg-splash"/><div className="relative z-10 flex flex-col items-center"><Logo large/><h1 className="mt-6 text-5xl font-semibold tracking-normal text-hero">Aera</h1><p className="mt-3 text-base text-hero-muted">Talk to your map.</p></div><div className="absolute bottom-12 z-10 flex flex-col items-center gap-3 text-xs text-hero-muted"><span>Tap to begin</span><span className="h-8 w-px bg-hero-muted/40"/></div></button>}
function Logo({large=false}:{large?:boolean}){return <div className={cn("relative flex items-center justify-center rounded-[1.4rem] bg-primary text-primary-foreground shadow-[0_0_36px_var(--primary-shadow)]",large?"size-20":"size-11")}><Navigation className={large?"size-10":"size-5"} fill="currentColor"/><span className="absolute -right-1 -top-1 size-3 rounded-full border-2 border-ink bg-success"/></div>}
const onboard=[{title:"Meet your intelligent map.",copy:"Plan routes, navigate and understand every journey with AI.",icon:Navigation},{title:"Talk instead of typing.",copy:"Ask your map about routes, traffic, distance, speed and travel time.",icon:AudioLines},{title:"Understand every trip.",copy:"See where you travelled, how long it took and how you moved.",icon:Gauge}];
function Onboarding({step,next,skip}:{step:number;next:()=>void;skip:()=>void}){const item=onboard[step];const Icon=item.icon;return <div className="flex h-full flex-col bg-background p-6"><div className="flex items-center justify-between"><Logo/><button onClick={skip} className="min-h-11 px-2 text-sm font-medium text-muted-foreground">Skip</button></div><div className="relative my-8 flex min-h-0 flex-1 items-center justify-center overflow-hidden rounded-[2rem] bg-map"><MapContainer mode={step===1?"routes":"default"}/><div className="absolute inset-0 bg-onboard"/><div className="relative z-10 flex size-24 items-center justify-center rounded-[2rem] border border-primary/25 bg-nav/70 text-primary shadow-[0_20px_60px_var(--primary-shadow)] backdrop-blur-xl"><Icon className="size-11" strokeWidth={1.5}/></div></div><div><div className="mb-5 flex gap-2">{onboard.map((_,i)=><span key={i} className={cn("h-1.5 rounded-full transition-all",i===step?"w-8 bg-primary":"w-2 bg-border")}/>)}</div><h2 className="max-w-sm text-4xl font-semibold leading-[1.04] tracking-normal">{item.title}</h2><p className="mt-4 max-w-sm text-base leading-relaxed text-muted-foreground">{item.copy}</p><PrimaryButton className="mt-7" onClick={next}>{step===2?"Get Started":"Next"}<ArrowRight className="ml-2 size-5"/></PrimaryButton></div></div>}
function Permission({onAllow,onSkip}:{onAllow:()=>void;onSkip:()=>void}){return <div className="flex h-full flex-col bg-background p-6"><Logo/><div className="flex flex-1 flex-col items-center justify-center text-center"><div className="relative flex size-32 items-center justify-center rounded-full bg-primary/10"><div className="absolute size-24 animate-ping-slow rounded-full border border-primary/20"/><MapPin className="size-12 text-primary" fill="currentColor"/></div><h2 className="mt-10 text-4xl font-semibold leading-tight">Your location powers your journey.</h2><p className="mt-4 max-w-sm text-base leading-relaxed text-muted-foreground">Location is used to show your position, provide navigation and record trips when you choose to start one.</p><div className="mt-7 flex items-center gap-2 rounded-full bg-success/10 px-4 py-2 text-xs font-semibold text-success"><ShieldCheck className="size-4"/>You control when trips are recorded</div></div><div className="space-y-3"><PrimaryButton onClick={onAllow}>Allow Location</PrimaryButton><SecondaryButton onClick={onSkip}>Not Now</SecondaryButton><button onClick={onSkip} className="h-10 w-full text-xs font-medium text-muted-foreground underline underline-offset-4">Privacy</button></div></div>}
function HomeMap({onSearch,onAI,onProfile,nav}:{onSearch:()=>void;onAI:()=>void;onProfile:()=>void;nav:(id:string)=>void}){return <div className="relative h-full"><MapContainer/><div className="absolute inset-x-0 top-0 z-10 h-40 bg-map-fade"/><div className="absolute inset-x-4 top-4 z-20 flex items-center gap-2 pt-safe"><button onClick={onSearch} className="flex h-14 flex-1 items-center gap-3 rounded-2xl border border-glass-border bg-nav/90 px-4 text-left shadow-xl backdrop-blur-2xl"><Search className="size-5 text-muted-foreground"/><span className="flex-1 text-sm font-medium text-foreground">Where do you want to go?</span><Mic className="size-5 text-primary"/></button><button onClick={onProfile} aria-label="Open profile" className="flex size-14 shrink-0 items-center justify-center rounded-2xl border border-glass-border bg-nav/90 text-foreground shadow-xl backdrop-blur-2xl"><UserRound className="size-5"/></button></div><div className="absolute right-4 top-[38%] z-20 space-y-2"><button aria-label="Recenter map" className="flex size-12 items-center justify-center rounded-2xl border border-glass-border bg-nav/90 shadow-lg backdrop-blur-xl"><LocateFixed className="size-5"/></button><LocationStatus/></div><GlassCard className="absolute inset-x-3 bottom-[92px] z-30 p-4"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Bot className="size-5"/></div><button onClick={onAI} className="min-w-0 flex-1 text-left"><div className="text-sm font-semibold">Ask your map</div><div className="mt-0.5 truncate text-xs text-muted-foreground">Fastest route to the airport?</div></button><button onClick={onAI} aria-label="Talk to Aera" className="flex size-11 items-center justify-center rounded-full bg-primary text-primary-foreground"><Mic className="size-5"/></button></div><div className="mt-3 flex gap-2 overflow-x-auto no-scrollbar">{["Where should I go?","Avoid traffic","How long will it take?"].map(x=><button key={x} onClick={onAI} className="shrink-0 rounded-full border border-border/70 bg-surface/60 px-3 py-2 text-xs text-foreground">{x}</button>)}</div></GlassCard><BottomNavigation active="home" onChange={nav}/></div>}
function Header({title,subtitle,back,right}:{title:string;subtitle?:string;back:()=>void;right?:React.ReactNode}){return <header className="flex min-h-20 items-center gap-3 px-5 pt-safe"><button onClick={back} aria-label="Go back" className="flex size-11 items-center justify-center rounded-2xl bg-secondary"><ArrowLeft className="size-5"/></button><div className="min-w-0 flex-1"><h1 className="truncate text-lg font-semibold">{title}</h1>{subtitle&&<p className="truncate text-xs text-muted-foreground">{subtitle}</p>}</div>{right}</header>}
function SearchScreen({back,select}:{back:()=>void;select:()=>void}){const ref=useRef<HTMLInputElement>(null);useEffect(()=>ref.current?.focus(),[]);return <div className="h-full overflow-y-auto bg-background pb-6"><div className="sticky top-0 z-10 bg-background/90 px-5 pb-4 pt-5 backdrop-blur-xl"><div className="flex items-center gap-2"><button onClick={back} aria-label="Go back" className="flex size-12 items-center justify-center rounded-2xl bg-secondary"><ArrowLeft className="size-5"/></button><label className="flex h-14 flex-1 items-center gap-3 rounded-2xl border border-primary/35 bg-surface px-4 shadow-[0_8px_28px_var(--primary-shadow)]"><Search className="size-5 text-primary"/><input ref={ref} placeholder="Search a place" className="min-w-0 flex-1 bg-transparent text-base outline-none placeholder:text-muted-foreground"/><Mic className="size-5 text-primary"/></label></div></div><section className="px-5 py-4"><h2 className="text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">Recent</h2><div className="mt-2">{places.slice(0,3).map((p,i)=><PlaceRow key={p.name} p={p} icon={i===2?<Plane/>:i===1?<Landmark/>:<History/>} onClick={select}/>)}</div></section><section className="px-5 py-3"><h2 className="text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">Saved</h2><div className="mt-2"><PlaceRow p={{...places[0],name:"Home",address:"Scheme No. 54, Indore"}} icon={<Home/>} onClick={select}/><PlaceRow p={{...places[0],name:"Work",address:"Vijay Nagar, Indore"}} icon={<Square/>} onClick={select}/></div></section><section className="px-5 py-3"><h2 className="text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">Suggested nearby</h2><div className="mt-2">{places.slice(3).map(p=><PlaceRow key={p.name} p={p} icon={<MapPin/>} onClick={select}/>)}</div></section></div>}
function PlaceRow({p,icon,onClick}:{p:{name:string;address:string;distance:string};icon:React.ReactNode;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center gap-3 border-b border-border/50 py-4 text-left last:border-0"><span className="flex size-11 items-center justify-center rounded-2xl bg-secondary text-muted-foreground [&>svg]:size-5">{icon}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{p.name}</span><span className="block truncate text-xs text-muted-foreground">{p.address}</span></span><span className="text-xs text-muted-foreground">{p.distance}</span></button>}
function Destination({back,directions,ask}:{back:()=>void;directions:()=>void;ask:()=>void}){return <div className="relative h-full"><MapContainer/><div className="absolute left-4 top-5 z-20"><button onClick={back} className="flex size-12 items-center justify-center rounded-2xl border border-glass-border bg-nav/90 backdrop-blur"><ArrowLeft className="size-5"/></button></div><FloatingCard className="absolute inset-x-3 bottom-3 z-20 p-5"><div className="flex items-start justify-between"><div><DemoPill/><h1 className="mt-3 text-3xl font-semibold">Devi Ahilya Bai Holkar Airport</h1><p className="mt-2 text-sm text-muted-foreground">Aerodrome Road, Indore</p></div></div><div className="mt-5 grid grid-cols-3 gap-2"><MetricCard compact label="Distance" value="12.4" unit="km"/><MetricCard compact label="Drive" value="24" unit="min"/><MetricCard compact label="Traffic" value="Med"/></div><div className="mt-4 grid grid-cols-2 gap-2"><PrimaryButton onClick={directions}><Navigation className="mr-2 size-5"/>Directions</PrimaryButton><SecondaryButton onClick={ask}><Bot className="mr-2 size-5"/>Ask AI</SecondaryButton></div><div className="mt-4 flex gap-2 overflow-x-auto no-scrollbar">{["Fastest route?","Avoid tolls","Less traffic","Scenic route"].map(x=><button onClick={ask} key={x} className="shrink-0 rounded-full bg-secondary px-3 py-2 text-xs">{x}</button>)}</div></FloatingCard></div>}
function RouteComparison({selected,setSelected,back,start}:{selected:string;setSelected:(id:string)=>void;back:()=>void;start:()=>void}){return <div className="relative h-full"><MapContainer mode="routes"/><div className="absolute inset-x-4 top-5 z-20 flex items-center justify-between"><button onClick={back} className="flex size-12 items-center justify-center rounded-2xl border border-glass-border bg-nav/90 backdrop-blur"><ArrowLeft className="size-5"/></button><DemoPill light/></div><div className="absolute inset-x-0 bottom-0 z-20 bg-sheet-fade pt-24"><div className="flex snap-x gap-3 overflow-x-auto px-4 pb-4 no-scrollbar">{routes.map(r=><RouteCard key={r.id} route={r} active={selected===r.id} onClick={()=>setSelected(r.id)}/>)}</div><div className="bg-background px-4 pb-5 pt-2"><PrimaryButton onClick={start}><Navigation className="mr-2 size-5" fill="currentColor"/>Start Navigation</PrimaryButton></div></div></div>}
function AIAssistant({back,nav}:{back:()=>void;nav:(id:string)=>void}){const [text,setText]=useState("");const [messages,setMessages]=useState<string[]>([]);const send=(prompt?:string)=>{const value=prompt??text;if(!value.trim())return;setMessages([...messages,value]);setText("")};return <div className="flex h-full flex-col bg-background"><Header title="AI Map Assistant" subtitle="Ask me anything about your journey" back={back} right={<DemoPill/>}/><div className="flex-1 space-y-4 overflow-y-auto px-5 py-5"><AIMessage role="ai">Hi, I’m Aera. I can compare your demo routes, explain trip patterns, or help you plan around traffic.</AIMessage><AIMessage role="user">Which route should I take?</AIMessage><AIMessage role="ai"><p>The fastest route is about <strong>24 minutes</strong>. The balanced route is 3 minutes longer but avoids the busiest intersection near Palasia.</p><div className="mt-3 rounded-xl bg-background/65 p-3"><div className="flex justify-between text-xs"><span className="font-semibold text-primary">Recommended</span><span>24 min · 12.4 km</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full w-4/5 rounded-full bg-primary"/></div></div></AIMessage>{messages.map((m,i)=><div key={i} className="space-y-4"><AIMessage role="user">{m}</AIMessage><AIMessage role="ai">Based on this demo journey, the fastest option uses AB Road. Traffic is moderate near Palasia, so the balanced route may feel calmer.</AIMessage></div>)}</div><div className="px-4 pb-[92px]"><div className="mb-3 flex gap-2 overflow-x-auto no-scrollbar">{["Fastest route","Avoid tolls","Avoid traffic","My last trip"].map(x=><button key={x} onClick={()=>send(x)} className="shrink-0 rounded-full border border-border bg-surface px-3 py-2 text-xs">{x}</button>)}</div><GlassCard className="flex items-end gap-2 p-2"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask anything..." aria-label="Ask Aera" className="min-h-11 max-h-24 flex-1 resize-none bg-transparent px-3 py-3 text-sm outline-none placeholder:text-muted-foreground"/><button onClick={()=>send()} aria-label="Send message" className="flex size-11 items-center justify-center rounded-full bg-primary text-primary-foreground"><ArrowRight className="size-5"/></button><button onClick={()=>send("What is the fastest route?")} aria-label="Speak to Aera" className="flex size-11 items-center justify-center rounded-full bg-primary text-primary-foreground"><Mic className="size-5"/></button></GlassCard></div><BottomNavigation active="ai" onChange={nav}/></div>}
function ActiveNavigation({expanded,setExpanded,end}:{expanded:boolean;setExpanded:(v:boolean)=>void;end:()=>void}){return <div className="relative h-full"><MapContainer mode="navigation"/><GlassCard className="absolute inset-x-3 top-3 z-20 p-4"><div className="flex items-center gap-4"><div className="flex size-16 shrink-0 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><ArrowRight className="size-9" strokeWidth={2.5}/></div><div><div className="text-3xl font-semibold tabular-nums">350 m</div><div className="mt-1 text-base font-medium">Turn right onto AB Road</div><div className="mt-1 text-xs text-muted-foreground">Then continue for 2.4 km</div></div></div></GlassCard><div className="absolute right-4 top-[40%] z-20 space-y-2">{[Volume2,LocateFixed,SlidersHorizontal].map((Icon,i)=><button key={i} aria-label={["Voice guidance","Recenter","Route options"][i]} className="flex size-12 items-center justify-center rounded-2xl border border-glass-border bg-nav/90 backdrop-blur-xl"><Icon className="size-5"/></button>)}</div><GlassCard className="absolute inset-x-3 bottom-3 z-30 overflow-hidden"><button onClick={()=>setExpanded(!expanded)} className="flex h-9 w-full items-center justify-center" aria-label={expanded?"Collapse trip metrics":"Expand trip metrics"}><ChevronDown className={cn("size-5 text-muted-foreground transition-transform",expanded&&"rotate-180")}/></button>{expanded&&<div className="grid grid-cols-3 gap-2 px-4 pb-3"><MetricCard compact label="Avg speed" value="31" unit="km/h"/><MetricCard compact label="Distance" value="8.4" unit="km"/><MetricCard compact label="Elapsed" value="18" unit="min"/></div>}<div className="grid grid-cols-3 gap-2 px-4 pb-4"><div><div className="text-3xl font-semibold">7:06</div><div className="text-xs text-muted-foreground">ETA · 24 min</div></div><div><div className="text-3xl font-semibold">12.4</div><div className="text-xs text-muted-foreground">km remaining</div></div><div><div className="text-3xl font-semibold">42</div><div className="text-xs text-muted-foreground">km/h</div></div></div><div className="flex gap-2 border-t border-border/60 p-3"><LocationStatus recording/><button onClick={end} className="ml-auto flex h-10 items-center gap-2 rounded-xl bg-error/12 px-4 text-sm font-semibold text-error"><Square className="size-3" fill="currentColor"/>End trip</button></div></GlassCard></div>}
function TripComplete({detail,ask}:{detail:()=>void;ask:()=>void}){return <div className="flex h-full flex-col overflow-y-auto bg-background p-5"><div className="flex flex-1 flex-col items-center justify-center py-8"><div className="relative flex size-28 items-center justify-center rounded-full bg-success/12"><div className="absolute size-24 animate-ping-slow rounded-full border border-success/25"/><Check className="size-12 text-success" strokeWidth={2.5}/></div><DemoPill/><h1 className="mt-5 text-4xl font-semibold">Trip complete</h1><p className="mt-2 text-sm text-muted-foreground">You arrived at Rajwada</p></div><div className="grid grid-cols-2 gap-2"><MetricCard label="Distance" value="14.8" unit="km"/><MetricCard label="Duration" value="32" unit="min"/><MetricCard label="Average speed" value="27" unit="km/h"/><MetricCard label="Maximum speed" value="64" unit="km/h"/></div><div className="mt-3 h-32 overflow-hidden rounded-3xl border border-border"><div className="relative h-full"><MapContainer mode="summary"/></div></div><div className="mt-4 space-y-2"><PrimaryButton onClick={detail}>View Trip</PrimaryButton><SecondaryButton onClick={ask}><Bot className="mr-2 size-5"/>Ask AI About This Trip</SecondaryButton></div></div>}
function TripHistory({open,nav}:{open:()=>void;nav:(id:string)=>void}){const [filter,setFilter]=useState("Week");return <div className="h-full overflow-y-auto bg-background pb-28"><header className="px-5 pb-4 pt-7"><div className="flex items-center justify-between"><div><DemoPill/><h1 className="mt-3 text-4xl font-semibold">Your journeys</h1><p className="mt-2 text-sm text-muted-foreground">A clear record of where you’ve been.</p></div><div className="flex size-12 items-center justify-center rounded-2xl bg-secondary"><History className="size-5"/></div></div><div className="mt-6 flex rounded-2xl bg-secondary p-1">{["Today","Week","Month","Custom"].map(f=><button key={f} onClick={()=>setFilter(f)} className={cn("h-10 flex-1 rounded-xl text-xs font-semibold",filter===f?"bg-card text-foreground shadow-sm":"text-muted-foreground")}>{f}</button>)}</div></header><div className="px-5"><div className="mb-4 grid grid-cols-2 gap-2"><MetricCard compact label="This week" value="54.2" unit="km"/><MetricCard compact label="Travel time" value="2h 14m"/></div>{["Today","Yesterday","This week"].map(date=><section key={date} className="mt-5"><h2 className="mb-2 text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">{date}</h2>{trips.filter(t=>t.date===date).map(t=><TripCard key={t.id} trip={t} onClick={open}/>)}</section>)}</div><BottomNavigation active="trips" onChange={nav}/></div>}
function TripDetails({back,replay,insight}:{back:()=>void;replay:()=>void;insight:()=>void}){return <div className="h-full overflow-y-auto bg-background pb-8"><Header back={back} title="Vijay Nagar → Rajwada" subtitle="Today · 6:42 PM" right={<DemoPill/>}/><div className="mx-5 h-52 overflow-hidden rounded-[1.75rem] border border-border"><div className="relative h-full"><MapContainer mode="summary"/></div></div><div className="grid grid-cols-2 gap-2 px-5 py-4"><MetricCard label="Distance" value="14.8" unit="km"/><MetricCard label="Duration" value="32" unit="min"/><MetricCard label="Average speed" value="27" unit="km/h"/><MetricCard label="Max speed" value="64" unit="km/h"/></div><section className="px-5"><h2 className="mb-3 text-lg font-semibold">Roads travelled</h2><div className="rounded-2xl bg-secondary p-4 text-sm"><div className="flex items-center gap-3"><span className="size-2 rounded-full bg-success"/>Vijay Nagar Square</div><div className="ml-[3px] h-7 border-l border-dashed border-border"/><div className="flex items-center gap-3"><span className="size-2 rounded-full bg-primary"/>AB Road · Palasia</div><div className="ml-[3px] h-7 border-l border-dashed border-border"/><div className="flex items-center gap-3"><span className="size-2 rounded-full bg-warning"/>Rajwada Palace</div></div></section><section className="px-5 py-5"><h2 className="mb-3 text-lg font-semibold">Performance</h2><div className="grid grid-cols-2 gap-x-5 rounded-2xl border border-border p-4 text-sm">{[["Moving time","26 min"],["Stopped time","6 min"],["Normal estimate","28 min"],["Actual time","32 min"]].map(([a,b])=><div key={a} className="flex justify-between border-b border-border/50 py-3"><span className="text-muted-foreground">{a}</span><strong>{b}</strong></div>)}</div></section><section className="px-5"><GlassCard className="p-4"><div className="flex items-center gap-2 text-sm font-semibold text-primary"><Sparkle className="size-4"/>AI insight</div><p className="mt-2 text-sm leading-relaxed text-foreground">Your demo trip took 4 minutes longer than the usual estimate. The longest pause occurred near Palasia.</p><button onClick={insight} className="mt-3 text-sm font-semibold text-primary">Explore insight →</button></GlassCard><PrimaryButton className="mt-4" onClick={replay}><Play className="mr-2 size-5" fill="currentColor"/>View 3D Replay</PrimaryButton></section></div>}
function Replay({back}:{back:()=>void}){const [playing,setPlaying]=useState(true);const [speed,setSpeed]=useState("1x");return <div className="relative h-full overflow-hidden bg-map"><MapContainer cinematic progress={playing?.72:.46}/><div className="absolute inset-0 bg-replay"/><div className="absolute inset-x-4 top-5 z-20 flex items-center justify-between"><button onClick={back} className="flex size-12 items-center justify-center rounded-2xl border border-glass-border bg-nav/85 backdrop-blur-xl"><ArrowLeft className="size-5"/></button><div className="text-center"><div className="text-sm font-semibold">Trip replay</div><div className="text-xs text-muted-foreground">Vijay Nagar → Rajwada</div></div><DemoPill/></div><GlassCard className="absolute left-4 top-28 z-20 grid grid-cols-1 gap-1 p-3"><div><span className="text-[10px] uppercase text-muted-foreground">Speed</span><div className="text-xl font-semibold">38 <span className="text-xs">km/h</span></div></div><div className="mt-2"><span className="text-[10px] uppercase text-muted-foreground">Distance</span><div className="text-lg font-semibold">7.2 km</div></div><div className="mt-2"><span className="text-[10px] uppercase text-muted-foreground">Elapsed</span><div className="text-lg font-semibold">16:42</div></div></GlassCard><GlassCard className="absolute inset-x-4 bottom-5 z-20 p-4"><div className="h-1.5 overflow-hidden rounded-full bg-border"><div className={cn("h-full w-[54%] rounded-full bg-primary",playing&&"animate-progress")}/></div><div className="mt-4 flex items-center justify-between"><div className="flex rounded-xl bg-secondary p-1">{["1x","2x","4x"].map(s=><button key={s} onClick={()=>setSpeed(s)} className={cn("h-9 w-11 rounded-lg text-xs font-semibold",speed===s&&"bg-card text-primary")}>{s}</button>)}</div><div className="flex gap-2"><button onClick={()=>setPlaying(false)} aria-label="Replay" className="flex size-11 items-center justify-center rounded-full bg-secondary"><RotateCcw className="size-4"/></button><button onClick={()=>setPlaying(!playing)} aria-label={playing?"Pause":"Play"} className="flex size-14 items-center justify-center rounded-full bg-primary text-primary-foreground">{playing?<Pause className="size-5" fill="currentColor"/>:<Play className="size-5" fill="currentColor"/>}</button></div></div></GlassCard></div>}
function Insights({back}:{back:()=>void}){return <div className="h-full overflow-y-auto bg-background pb-8"><Header back={back} title="Today’s journey" subtitle="AI-generated demo insight" right={<DemoPill/>}/><section className="px-5 pt-4"><GlassCard className="overflow-hidden p-5"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Bot className="size-5"/></div><div><div className="text-xs font-semibold uppercase tracking-[.12em] text-primary">Journey brief</div><h2 className="text-xl font-semibold">14.8 km in 32 minutes</h2></div></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">This prototype insight uses sample journey data and does not represent live tracking.</p></GlassCard><h2 className="mb-3 mt-7 text-xl font-semibold">What shaped your trip</h2><div className="space-y-3">{[[Clock3,"26 minutes moving","Most of your trip maintained a steady pace."],[Pause,"6 minutes stopped","The longest demo delay occurred near Palasia."],[Gauge,"31 km/h moving average","A consistent pace across central Indore."],[RouteIcon,"4 minutes over estimate","This sample route was slower than its usual estimate."]].map(([Icon,title,copy])=><div key={String(title)} className="flex gap-4 rounded-2xl border border-border bg-surface/70 p-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="size-5"/></div><div><h3 className="text-sm font-semibold">{String(title)}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{String(copy)}</p></div></div>)}</div><div className="mt-6 rounded-2xl bg-secondary p-4"><div className="flex items-end gap-2 h-24">{[42,62,48,85,58,72,52,68,44,60].map((h,i)=><div key={i} className="flex-1 rounded-t-md bg-primary/70" style={{height:`${h}%`}}/>)}</div><div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>Start</span><span>Palasia</span><span>Rajwada</span></div></div></section></div>}
function Profile({openSettings,openTrips,openPrivacy,nav}:{openSettings:()=>void;openTrips:()=>void;openPrivacy:()=>void;nav:(id:string)=>void}){return <div className="h-full overflow-y-auto bg-background pb-28"><header className="bg-profile px-5 pb-7 pt-8"><div className="flex items-center justify-between"><Logo/><button onClick={openSettings} aria-label="Settings" className="flex size-11 items-center justify-center rounded-2xl bg-secondary"><Settings2 className="size-5"/></button></div><div className="mt-8 flex items-center gap-4"><div className="flex size-20 items-center justify-center rounded-3xl bg-primary/15 text-primary"><UserRound className="size-9"/></div><div><h1 className="text-3xl font-semibold">Dheeraj</h1><p className="mt-1 text-sm text-muted-foreground">Thoughtful traveller · Indore</p></div></div></header><div className="grid grid-cols-2 gap-2 px-5 py-5"><MetricCard label="Total distance" value="1,248" unit="km"/><MetricCard label="Trips" value="86"/><MetricCard label="Time travelled" value="42" unit="h"/><MetricCard label="Average trip" value="14.5" unit="km"/></div><div className="px-5"><div className="rounded-2xl bg-surface px-4"><ListRow icon={<History className="size-5"/>} label="Trip History" onClick={openTrips}/><ListRow icon={<MapPin className="size-5"/>} label="Saved Places"/><ListRow icon={<ShieldCheck className="size-5"/>} label="Privacy" onClick={openPrivacy}/><ListRow icon={<LocateFixed className="size-5"/>} label="Location Settings" onClick={openPrivacy}/><ListRow icon={<Bot className="size-5"/>} label="AI Settings" onClick={openSettings}/><ListRow icon={<Bell className="size-5"/>} label="Notifications"/><ListRow icon={<Info className="size-5"/>} label="About Aera"/></div></div><BottomNavigation active="profile" onChange={nav}/></div>}
function Settings({back,privacy}:{back:()=>void;privacy:()=>void}){return <div className="h-full overflow-y-auto bg-background pb-8"><Header back={back} title="Settings"/><SettingsGroup title="Navigation"><ToggleRow label="Voice guidance" detail="Spoken turn instructions" initial/><ToggleRow label="Avoid tolls"/><ToggleRow label="Avoid highways"/><ChoiceRow label="Units" value="Metric"/><ChoiceRow label="Route preference" value="Balanced"/></SettingsGroup><SettingsGroup title="Location"><ToggleRow label="Location permission" detail="Used only while using the app" initial/><ToggleRow label="Trip recording" detail="Starts only when you choose"/><ToggleRow label="Background location" detail="Needed to keep a chosen trip recording while the screen is off"/></SettingsGroup><SettingsGroup title="AI"><ToggleRow label="AI voice" initial/><ChoiceRow label="Response style" value="Concise"/><ToggleRow label="Conversation history" detail="Store chats on this device"/></SettingsGroup><SettingsGroup title="Privacy"><ListRow icon={<ShieldCheck className="size-5"/>} label="Data controls" onClick={privacy}/><ListRow icon={<Trash2 className="size-5"/>} label="Delete trip history"/><ListRow icon={<LockKeyhole className="size-5"/>} label="Privacy Policy" onClick={privacy}/></SettingsGroup></div>}
function SettingsGroup({title,children}:{title:string;children:React.ReactNode}){return <section className="px-5 py-3"><h2 className="mb-2 text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">{title}</h2><div className="rounded-2xl bg-surface px-4">{children}</div></section>}
function ToggleRow({label,detail,initial=false}:{label:string;detail?:string;initial?:boolean}){const [on,setOn]=useState(initial);return <div className="flex min-h-16 items-center gap-3 border-b border-border/50 py-3 last:border-0"><div className="flex-1"><div className="text-sm font-medium">{label}</div>{detail&&<div className="mt-0.5 text-xs leading-relaxed text-muted-foreground">{detail}</div>}</div><Switch checked={on} onCheckedChange={setOn} aria-label={label}/></div>}
function ChoiceRow({label,value}:{label:string;value:string}){return <button className="flex min-h-14 w-full items-center border-b border-border/50 py-3 text-sm last:border-0"><span className="flex-1 text-left font-medium">{label}</span><span className="text-muted-foreground">{value}</span><ChevronRight className="ml-2 size-4 text-muted-foreground"/></button>}
function Privacy({back}:{back:()=>void}){const [location,setLocation]=useState(true);const [recording,setRecording]=useState(false);return <div className="h-full overflow-y-auto bg-background pb-8"><Header back={back} title="Privacy & location" subtitle="Clear controls, always"/><div className="px-5 pt-4"><div className="rounded-[1.75rem] bg-secondary p-5"><ShieldCheck className="size-8 text-success"/><h2 className="mt-5 text-2xl font-semibold">Your journey stays yours.</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Aera only uses location for the experience you choose. This prototype does not collect, store, or track real location data.</p></div><div className="mt-5 space-y-3"><StatusControl title="Location" active={location} onChange={setLocation} detail="Shows your position while the app is open."/><StatusControl title="Trip recording" active={recording} onChange={setRecording} detail="Records only after you explicitly start a trip."/><StatusControl title="Background location" active={false} onChange={()=>{}} detail="Would keep an active trip recording when your screen is off. Not enabled in this prototype." disabled/></div><div className="mt-6 rounded-2xl border border-error/20 bg-error/5 px-4"><ListRow icon={<Trash2 className="size-5 text-error"/>} label="Delete trip history"/><ListRow icon={<X className="size-5 text-error"/>} label="Delete account"/></div></div></div>}
function StatusControl({title,active,onChange,detail,disabled=false}:{title:string;active:boolean;onChange:(v:boolean)=>void;detail:string;disabled?:boolean}){return <div className="rounded-2xl border border-border bg-surface p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={cn("size-2.5 rounded-full",active?"bg-success":"bg-muted-foreground")}/><span className="text-sm font-semibold">{title} {active?"ON":"OFF"}</span></div><Switch disabled={disabled} checked={active} onCheckedChange={onChange} aria-label={title}/></div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{detail}</p></div>}
